# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=datetime.datetime(2016, 7, 16, 14, 47, 53, 12915, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
